packages:
  - packages/*
  - support/*
  - test/*

minimumReleaseAge: 2880

onlyBuiltDependencies:
  - core-js
  - core-js-pure
  - esbuild
  - nx
  - unrs-resolver

minimumReleaseAgeExclude:
  # Renovate security update: handlebars@4.7.9
  - handlebars@4.7.9
