const { PLUGIN_NAME } = require("./plugin");

const {
  ELEMENT_TYPES,
  EXTERNAL,
  ENTRY_POINT,
  NO_IGNORED,
  ONLY_KNOWN,
  NO_PRIVATE,

  // To be removed
  PREFER_RECOGNIZED_TYPES,
} = require("./rules");

module.exports = {
  ELEMENTS: `${PLUGIN_NAME}/elements`,
  IGNORE: `${PLUGIN_NAME}/ignore`,
  RULE_ELEMENT_TYPES: `${PLUGIN_NAME}/${ELEMENT_TYPES}`,
  RULE_EXTERNAL: `${PLUGIN_NAME}/${EXTERNAL}`,
  RULE_ENTRY_POINT: `${PLUGIN_NAME}/${ENTRY_POINT}`,
  RULE_NO_IGNORED: `${PLUGIN_NAME}/${NO_IGNORED}`,
  RULE_ONLY_KNOWN: `${PLUGIN_NAME}/${ONLY_KNOWN}`,
  RULE_NO_PRIVATE: `${PLUGIN_NAME}/${NO_PRIVATE}`,

  // Deprecated
  TYPES: `${PLUGIN_NAME}/types`,
  ALIAS: `${PLUGIN_NAME}/alias`,

  // To be removed
  RULE_PREFER_RECOGNIZED_TYPES: `${PLUGIN_NAME}/${PREFER_RECOGNIZED_TYPES}`,
};
