const { PLUGIN_NAME } = require("./plugin");

const {
  NO_PRIVATE,
  ENTRY_POINT,
  ALLOWED_TYPES,
  NO_EXTERNAL,
  PREFER_RECOGNIZED_TYPES,
  NO_IMPORT_NOT_RECOGNIZED_TYPES,
  NO_IMPORT_IGNORED,
} = require("./rules");

module.exports = {
  TYPES: `${PLUGIN_NAME}/types`,
  IGNORE: `${PLUGIN_NAME}/ignore`,
  ALIAS: `${PLUGIN_NAME}/alias`,
  RULE_NO_PRIVATE: `${PLUGIN_NAME}/${NO_PRIVATE}`,
  RULE_ENTRY_POINT: `${PLUGIN_NAME}/${ENTRY_POINT}`,
  RULE_ALLOWED_TYPES: `${PLUGIN_NAME}/${ALLOWED_TYPES}`,
  RULE_NO_EXTERNAL: `${PLUGIN_NAME}/${NO_EXTERNAL}`,
  RULE_PREFER_RECOGNIZED_TYPES: `${PLUGIN_NAME}/${PREFER_RECOGNIZED_TYPES}`,
  RULE_NO_IMPORT_NOT_RECOGNIZED_TYPES: `${PLUGIN_NAME}/${NO_IMPORT_NOT_RECOGNIZED_TYPES}`,
  RULE_NO_IMPORT_IGNORED: `${PLUGIN_NAME}/${NO_IMPORT_IGNORED}`,
};
