name: publish-to-npm
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    if: contains(github.event.release.target_commitish, '-beta.') == false
    steps:
    - uses: actions/checkout@v5
    - uses: ./.github/actions/install
    - run: pnpm nx run-many -t check:all --all
    - run: pnpm -r publish --no-git-checks
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
