name: publish-to-npm
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    if: contains(github.event.release.target_commitish, '-beta.') == false
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/install
    - run: pnpm nx run-many -t check:all --all
    - run: pnpm -r publish --no-git-checks
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - uses: MerthinTechnologies/edit-json-action@v1
      with:
        filename: './packages/eslint-plugin-boundaries/package.json'
        key: 'name'
        value: 'eslint-plugin-boundaries'
    - run: pnpm -r publish --no-git-checks
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
